<?php
$secure_page=0;
$this_page = "guestbook";
include 'header.php';
?>
<center>
<h1>XMEC Guestbook</h1>
</center>
<P>Visitors can sign in the XMEC Guestbook. Please <a href="addguest.php">post</a> your valuable remarks in this forum.</P>
<hr>
<!--begin-->
<center><table border="0" cellpadding="0" cellspacing="0" width="90%"> <tbody> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_top.gif" height="4"><img src="images/tb_left_topt.gif" height="4" width="8"></td> <td align="right" background="images/tb_top.gif" height="4"><img src="images/tb_right_topt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="top" width="4"><img src="images/tb_left_topb.gif" height="6" width="3"></td> <td colspan="2" rowspan="2"><table width='100%' border=0><tr><td><b> Message on Friday</b><hr></td></tr>
<tr bgcolor="#cfddd1"><td><a href="http://xmec.net/view_details.php?.s=1&id=">Robi</a></td></tr><tr bgcolor="#cfddd1"><td>
 - Thursday, December 16, 2004 at 20:38:34 (PST)<p>

</td></tr></table></td> <td background="images/tb_right.gif" height="50%" valign="top" width="4"><img src="images/tb_right_topb.gif" height="6" width="3"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="bottom" width="4"><img src="images/tb_left_bottomb.gif" height="6" width="3"></td> <td background="images/tb_right.gif" height="50%" valign="bottom" width="4"><img src="images/tb_right_bottomb.gif" height="6" width="3"></td> </tr> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_bottom.gif" height="4"><img src="images/tb_left_bottomt.gif" height="4" width="8"></td> <td align="right" background="images/tb_bottom.gif" height="4"><img src="images/tb_right_bottomt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> </tbody> </table><center><br><center><table border="0" cellpadding="0" cellspacing="0" width="90%"> <tbody> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_top.gif" height="4"><img src="images/tb_left_topt.gif" height="4" width="8"></td> <td align="right" background="images/tb_top.gif" height="4"><img src="images/tb_right_topt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="top" width="4"><img src="images/tb_left_topb.gif" height="6" width="3"></td> <td colspan="2" rowspan="2"><table width='100%' border=0><tr><td><b> sdfsf</b><hr></td></tr>
<tr bgcolor="#cfddd1"><td><a href="http://xmec.net/view_details.php?.s=1&id=">James</a></td></tr><tr bgcolor="#cfddd1"><td>
 Thames - Tuesday, December 14, 2004 at 00:29:05 (PST)<p>

</td></tr></table></td> <td background="images/tb_right.gif" height="50%" valign="top" width="4"><img src="images/tb_right_topb.gif" height="6" width="3"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="bottom" width="4"><img src="images/tb_left_bottomb.gif" height="6" width="3"></td> <td background="images/tb_right.gif" height="50%" valign="bottom" width="4"><img src="images/tb_right_bottomb.gif" height="6" width="3"></td> </tr> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_bottom.gif" height="4"><img src="images/tb_left_bottomt.gif" height="4" width="8"></td> <td align="right" background="images/tb_bottom.gif" height="4"><img src="images/tb_right_bottomt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> </tbody> </table><center><br><center><table border="0" cellpadding="0" cellspacing="0" width="90%"> <tbody> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_top.gif" height="4"><img src="images/tb_left_topt.gif" height="4" width="8"></td> <td align="right" background="images/tb_top.gif" height="4"><img src="images/tb_right_topt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="top" width="4"><img src="images/tb_left_topb.gif" height="6" width="3"></td> <td colspan="2" rowspan="2"><table width='100%' border=0><tr><td><b> Tested Login</b><hr></td></tr>
<tr bgcolor="#cfddd1"><td><a href="http://xmec.net/view_details.php?.s=1&id=">Robi</a></td></tr><tr bgcolor="#cfddd1"><td>
 - Tuesday, December 14, 2004 at 00:26:27 (PST)<p>

</td></tr></table></td> <td background="images/tb_right.gif" height="50%" valign="top" width="4"><img src="images/tb_right_topb.gif" height="6" width="3"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="bottom" width="4"><img src="images/tb_left_bottomb.gif" height="6" width="3"></td> <td background="images/tb_right.gif" height="50%" valign="bottom" width="4"><img src="images/tb_right_bottomb.gif" height="6" width="3"></td> </tr> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_bottom.gif" height="4"><img src="images/tb_left_bottomt.gif" height="4" width="8"></td> <td align="right" background="images/tb_bottom.gif" height="4"><img src="images/tb_right_bottomt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> </tbody> </table><center><br><center><table border="0" cellpadding="0" cellspacing="0" width="90%"> <tbody> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_top.gif" height="4"><img src="images/tb_left_topt.gif" height="4" width="8"></td> <td align="right" background="images/tb_top.gif" height="4"><img src="images/tb_right_topt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="top" width="4"><img src="images/tb_left_topb.gif" height="6" width="3"></td> <td colspan="2" rowspan="2"><table width='100%' border=0><tr><td><b> Testing</b><hr></td></tr>
<tr bgcolor="#cfddd1"><td><a href="http://xmec.net/view_details.php?.s=1&id="> </a></td></tr><tr bgcolor="#cfddd1"><td>
 - Tuesday, December 14, 2004 at 00:24:06 (PST)<p>

</td></tr></table></td> <td background="images/tb_right.gif" height="50%" valign="top" width="4"><img src="images/tb_right_topb.gif" height="6" width="3"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="bottom" width="4"><img src="images/tb_left_bottomb.gif" height="6" width="3"></td> <td background="images/tb_right.gif" height="50%" valign="bottom" width="4"><img src="images/tb_right_bottomb.gif" height="6" width="3"></td> </tr> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_bottom.gif" height="4"><img src="images/tb_left_bottomt.gif" height="4" width="8"></td> <td align="right" background="images/tb_bottom.gif" height="4"><img src="images/tb_right_bottomt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> </tbody> </table><center><br><center><table border="0" cellpadding="0" cellspacing="0" width="90%"> <tbody> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_top.gif" height="4"><img src="images/tb_left_topt.gif" height="4" width="8"></td> <td align="right" background="images/tb_top.gif" height="4"><img src="images/tb_right_topt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="top" width="4"><img src="images/tb_left_topb.gif" height="6" width="3"></td> <td colspan="2" rowspan="2"><table width='100%' border=0><tr><td><b> sfjsdf</b><hr></td></tr>
<tr bgcolor="#cfddd1"><td><a href="http://xmec.net/view_details.php?.s=1&id=">Test1 name</a></td></tr><tr bgcolor="#cfddd1"><td>
 - Wednesday, December 08, 2004 at 23:24:37 (PST)<p>

</td></tr></table></td> <td background="images/tb_right.gif" height="50%" valign="top" width="4"><img src="images/tb_right_topb.gif" height="6" width="3"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="bottom" width="4"><img src="images/tb_left_bottomb.gif" height="6" width="3"></td> <td background="images/tb_right.gif" height="50%" valign="bottom" width="4"><img src="images/tb_right_bottomb.gif" height="6" width="3"></td> </tr> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_bottom.gif" height="4"><img src="images/tb_left_bottomt.gif" height="4" width="8"></td> <td align="right" background="images/tb_bottom.gif" height="4"><img src="images/tb_right_bottomt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> </tbody> </table><center><br><center><table border="0" cellpadding="0" cellspacing="0" width="90%"> <tbody> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_top.gif" height="4"><img src="images/tb_left_topt.gif" height="4" width="8"></td> <td align="right" background="images/tb_top.gif" height="4"><img src="images/tb_right_topt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="top" width="4"><img src="images/tb_left_topb.gif" height="6" width="3"></td> <td colspan="2" rowspan="2"><table width='100%' border=0><tr><td><b> Commenting</b><hr></td></tr>
<tr bgcolor="#cfddd1"><td>33/1995&nbsp;&nbsp;<a href="http://xmec.net/view_details.php?.s=1&id=33/1995">Tst name</a></td></tr><tr bgcolor="#cfddd1"><td>
 USA - Wednesday, December 08, 2004 at 23:23:21 (PST)<p>

</td></tr></table></td> <td background="images/tb_right.gif" height="50%" valign="top" width="4"><img src="images/tb_right_topb.gif" height="6" width="3"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="bottom" width="4"><img src="images/tb_left_bottomb.gif" height="6" width="3"></td> <td background="images/tb_right.gif" height="50%" valign="bottom" width="4"><img src="images/tb_right_bottomb.gif" height="6" width="3"></td> </tr> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_bottom.gif" height="4"><img src="images/tb_left_bottomt.gif" height="4" width="8"></td> <td align="right" background="images/tb_bottom.gif" height="4"><img src="images/tb_right_bottomt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> </tbody> </table><center><br><center><table border="0" cellpadding="0" cellspacing="0" width="90%"> <tbody> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_top.gif" height="4"><img src="images/tb_left_topt.gif" height="4" width="8"></td> <td align="right" background="images/tb_top.gif" height="4"><img src="images/tb_right_topt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="top" width="4"><img src="images/tb_left_topb.gif" height="6" width="3"></td> <td colspan="2" rowspan="2"><table width='100%' border=0><tr><td><b> Message</b><hr></td></tr>
<tr bgcolor="#cfddd1"><td><a href="http://xmec.net/view_details.php?.s=1&id=">Robi</a></td></tr><tr bgcolor="#cfddd1"><td>
 Place - Wednesday, December 08, 2004 at 22:05:54 (PST)<p>

</td></tr></table></td> <td background="images/tb_right.gif" height="50%" valign="top" width="4"><img src="images/tb_right_topb.gif" height="6" width="3"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="bottom" width="4"><img src="images/tb_left_bottomb.gif" height="6" width="3"></td> <td background="images/tb_right.gif" height="50%" valign="bottom" width="4"><img src="images/tb_right_bottomb.gif" height="6" width="3"></td> </tr> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_bottom.gif" height="4"><img src="images/tb_left_bottomt.gif" height="4" width="8"></td> <td align="right" background="images/tb_bottom.gif" height="4"><img src="images/tb_right_bottomt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> </tbody> </table><center><br><center><table border="0" cellpadding="0" cellspacing="0" width="90%"> <tbody> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_top.gif" height="4"><img src="images/tb_left_topt.gif" height="4" width="8"></td> <td align="right" background="images/tb_top.gif" height="4"><img src="images/tb_right_topt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="top" width="4"><img src="images/tb_left_topb.gif" height="6" width="3"></td> <td colspan="2" rowspan="2"><table width='100%' border=0><tr><td><b> Message</b><hr></td></tr>
<tr bgcolor="#cfddd1"><td>Robi&nbsp;&nbsp;<a href="http://xmec.net/view_details.php?.s=1&id=Robi"> </a></td></tr><tr bgcolor="#cfddd1"><td>
email, City Country - Wednesday, December 08, 2004 at 22:05:18 (PST)<p>

</td></tr></table></td> <td background="images/tb_right.gif" height="50%" valign="top" width="4"><img src="images/tb_right_topb.gif" height="6" width="3"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="bottom" width="4"><img src="images/tb_left_bottomb.gif" height="6" width="3"></td> <td background="images/tb_right.gif" height="50%" valign="bottom" width="4"><img src="images/tb_right_bottomb.gif" height="6" width="3"></td> </tr> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_bottom.gif" height="4"><img src="images/tb_left_bottomt.gif" height="4" width="8"></td> <td align="right" background="images/tb_bottom.gif" height="4"><img src="images/tb_right_bottomt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> </tbody> </table><center><br><center><table border="0" cellpadding="0" cellspacing="0" width="90%"> <tbody> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_top.gif" height="4"><img src="images/tb_left_topt.gif" height="4" width="8"></td> <td align="right" background="images/tb_top.gif" height="4"><img src="images/tb_right_topt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="top" width="4"><img src="images/tb_left_topb.gif" height="6" width="3"></td> <td colspan="2" rowspan="2"><table width='100%' border=0><tr><td><b> dfsf</b><hr></td></tr>
<tr bgcolor="#cfddd1"><td>Robi&nbsp;&nbsp;<a href="http://xmec.net/view_details.php?.s=1&id=Robi"> </a></td></tr><tr bgcolor="#cfddd1"><td>
 sdfsd - Wednesday, December 08, 2004 at 22:04:41 (PST)<p>

</td></tr></table></td> <td background="images/tb_right.gif" height="50%" valign="top" width="4"><img src="images/tb_right_topb.gif" height="6" width="3"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="bottom" width="4"><img src="images/tb_left_bottomb.gif" height="6" width="3"></td> <td background="images/tb_right.gif" height="50%" valign="bottom" width="4"><img src="images/tb_right_bottomb.gif" height="6" width="3"></td> </tr> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_bottom.gif" height="4"><img src="images/tb_left_bottomt.gif" height="4" width="8"></td> <td align="right" background="images/tb_bottom.gif" height="4"><img src="images/tb_right_bottomt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> </tbody> </table><center><br><center><table border="0" cellpadding="0" cellspacing="0" width="90%"> <tbody> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_top.gif" height="4"><img src="images/tb_left_topt.gif" height="4" width="8"></td> <td align="right" background="images/tb_top.gif" height="4"><img src="images/tb_right_topt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="top" width="4"><img src="images/tb_left_topb.gif" height="6" width="3"></td> <td colspan="2" rowspan="2"><table width='100%' border=0><tr><td><b> Testing </b><hr></td></tr>
<tr bgcolor="#cfddd1"><td>webmasters&nbsp;&nbsp;<a href="http://xmec.net/view_details.php?.s=1&id=webmasters">Ready</a></td></tr><tr bgcolor="#cfddd1"><td>
 Place USA - Thursday, October 07, 2004 at 05:03:00 (PDT)<p>

</td></tr></table></td> <td background="images/tb_right.gif" height="50%" valign="top" width="4"><img src="images/tb_right_topb.gif" height="6" width="3"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="bottom" width="4"><img src="images/tb_left_bottomb.gif" height="6" width="3"></td> <td background="images/tb_right.gif" height="50%" valign="bottom" width="4"><img src="images/tb_right_bottomb.gif" height="6" width="3"></td> </tr> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_bottom.gif" height="4"><img src="images/tb_left_bottomt.gif" height="4" width="8"></td> <td align="right" background="images/tb_bottom.gif" height="4"><img src="images/tb_right_bottomt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> </tbody> </table><center><br><center><table border="0" cellpadding="0" cellspacing="0" width="90%"> <tbody> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_top.gif" height="4"><img src="images/tb_left_topt.gif" height="4" width="8"></td> <td align="right" background="images/tb_top.gif" height="4"><img src="images/tb_right_topt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="top" width="4"><img src="images/tb_left_topb.gif" height="6" width="3"></td> <td colspan="2" rowspan="2"><table width='100%' border=0><tr><td><b> Basdfsdfsdf</b><hr></td></tr>
<tr bgcolor="#cfddd1"><td><a href="http://xmec.net/view_details.php?.s=1&id=">Joby</a></td></tr><tr bgcolor="#cfddd1"><td>
 Chicago - Friday, August 13, 2004 at 07:56:00 (PDT)<p>

</td></tr></table></td> <td background="images/tb_right.gif" height="50%" valign="top" width="4"><img src="images/tb_right_topb.gif" height="6" width="3"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="bottom" width="4"><img src="images/tb_left_bottomb.gif" height="6" width="3"></td> <td background="images/tb_right.gif" height="50%" valign="bottom" width="4"><img src="images/tb_right_bottomb.gif" height="6" width="3"></td> </tr> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_bottom.gif" height="4"><img src="images/tb_left_bottomt.gif" height="4" width="8"></td> <td align="right" background="images/tb_bottom.gif" height="4"><img src="images/tb_right_bottomt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> </tbody> </table><center><br><center><table border="0" cellpadding="0" cellspacing="0" width="90%"> <tbody> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_top.gif" height="4"><img src="images/tb_left_topt.gif" height="4" width="8"></td> <td align="right" background="images/tb_top.gif" height="4"><img src="images/tb_right_topt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="top" width="4"><img src="images/tb_left_topb.gif" height="6" width="3"></td> <td colspan="2" rowspan="2"><table width='100%' border=0><tr><td><b> sersfsdfsdf</b><hr></td></tr>
<tr bgcolor="#cfddd1"><td>33/1995&nbsp;&nbsp;<a href="http://xmec.net/view_details.php?.s=1&id=33/1995">Tames</a></td></tr><tr bgcolor="#cfddd1"><td>
 Germany - Friday, August 13, 2004 at 07:53:35 (PDT)<p>

</td></tr></table></td> <td background="images/tb_right.gif" height="50%" valign="top" width="4"><img src="images/tb_right_topb.gif" height="6" width="3"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="bottom" width="4"><img src="images/tb_left_bottomb.gif" height="6" width="3"></td> <td background="images/tb_right.gif" height="50%" valign="bottom" width="4"><img src="images/tb_right_bottomb.gif" height="6" width="3"></td> </tr> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_bottom.gif" height="4"><img src="images/tb_left_bottomt.gif" height="4" width="8"></td> <td align="right" background="images/tb_bottom.gif" height="4"><img src="images/tb_right_bottomt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> </tbody> </table><center><br><center><table border="0" cellpadding="0" cellspacing="0" width="90%"> <tbody> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_top.gif" height="4"><img src="images/tb_left_topt.gif" height="4" width="8"></td> <td align="right" background="images/tb_top.gif" height="4"><img src="images/tb_right_topt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="top" width="4"><img src="images/tb_left_topb.gif" height="6" width="3"></td> <td colspan="2" rowspan="2"><table width='100%' border=0><tr><td><b> testing</b><hr></td></tr>
<tr bgcolor="#cfddd1"><td>33/1995&nbsp;&nbsp;<a href="http://xmec.net/view_details.php?.s=1&id=33/1995">James</a></td></tr><tr bgcolor="#cfddd1"><td>
 TVM - Friday, August 13, 2004 at 07:46:45 (PDT)<p>

</td></tr></table></td> <td background="images/tb_right.gif" height="50%" valign="top" width="4"><img src="images/tb_right_topb.gif" height="6" width="3"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="bottom" width="4"><img src="images/tb_left_bottomb.gif" height="6" width="3"></td> <td background="images/tb_right.gif" height="50%" valign="bottom" width="4"><img src="images/tb_right_bottomb.gif" height="6" width="3"></td> </tr> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_bottom.gif" height="4"><img src="images/tb_left_bottomt.gif" height="4" width="8"></td> <td align="right" background="images/tb_bottom.gif" height="4"><img src="images/tb_right_bottomt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> </tbody> </table><center><br><center><table border="0" cellpadding="0" cellspacing="0" width="90%"> <tbody> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_top.gif" height="4"><img src="images/tb_left_topt.gif" height="4" width="8"></td> <td align="right" background="images/tb_top.gif" height="4"><img src="images/tb_right_topt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="top" width="4"><img src="images/tb_left_topb.gif" height="6" width="3"></td> <td colspan="2" rowspan="2"><table width='100%' border=0><tr><td><b> testing</b><hr></td></tr>
<tr bgcolor="#cfddd1"><td>33/1995&nbsp;&nbsp;<a href="http://xmec.net/view_details.php?.s=1&id=33/1995">James</a></td></tr><tr bgcolor="#cfddd1"><td>
 TVM - Friday, August 13, 2004 at 07:46:28 (PDT)<p>

</td></tr></table></td> <td background="images/tb_right.gif" height="50%" valign="top" width="4"><img src="images/tb_right_topb.gif" height="6" width="3"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="bottom" width="4"><img src="images/tb_left_bottomb.gif" height="6" width="3"></td> <td background="images/tb_right.gif" height="50%" valign="bottom" width="4"><img src="images/tb_right_bottomb.gif" height="6" width="3"></td> </tr> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_bottom.gif" height="4"><img src="images/tb_left_bottomt.gif" height="4" width="8"></td> <td align="right" background="images/tb_bottom.gif" height="4"><img src="images/tb_right_bottomt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> </tbody> </table><center><br><center><table border="0" cellpadding="0" cellspacing="0" width="90%"> <tbody> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_top.gif" height="4"><img src="images/tb_left_topt.gif" height="4" width="8"></td> <td align="right" background="images/tb_top.gif" height="4"><img src="images/tb_right_topt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="top" width="4"><img src="images/tb_left_topb.gif" height="6" width="3"></td> <td colspan="2" rowspan="2"><table width='100%' border=0><tr><td><b> Funny Guestbook</b><hr></td></tr>
<tr bgcolor="#cfddd1"><td>James&nbsp;&nbsp;<a href="http://xmec.net/view_details.php?.s=1&id=James"> </a></td></tr><tr bgcolor="#cfddd1"><td>
james@gmail.com, TVM India - Friday, August 13, 2004 at 07:45:23 (PDT)<p>

</td></tr></table></td> <td background="images/tb_right.gif" height="50%" valign="top" width="4"><img src="images/tb_right_topb.gif" height="6" width="3"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="bottom" width="4"><img src="images/tb_left_bottomb.gif" height="6" width="3"></td> <td background="images/tb_right.gif" height="50%" valign="bottom" width="4"><img src="images/tb_right_bottomb.gif" height="6" width="3"></td> </tr> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_bottom.gif" height="4"><img src="images/tb_left_bottomt.gif" height="4" width="8"></td> <td align="right" background="images/tb_bottom.gif" height="4"><img src="images/tb_right_bottomt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> </tbody> </table><center><br><center><table border="0" cellpadding="0" cellspacing="0" width="90%"> <tbody> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_top.gif" height="4"><img src="images/tb_left_topt.gif" height="4" width="8"></td> <td align="right" background="images/tb_top.gif" height="4"><img src="images/tb_right_topt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="top" width="4"><img src="images/tb_left_topb.gif" height="6" width="3"></td> <td colspan="2" rowspan="2"><table width='100%' border=0><tr><td><b> Heard that some MEC students are NOT doing their project by themselves.<br>
Instead of that, they ask some external people/organizations , to do their<br>
project, and pay for that. If the information is correct, I think it is very<br>
serious issue, which will reduce the quality of our great MEC.</b><hr></td></tr>
<tr bgcolor="#cfddd1"><td>33/1995&nbsp;&nbsp;<a href="http://xmec.net/view_details.php?.s=1&id=33/1995">Enemy</a></td></tr><tr bgcolor="#cfddd1"><td>
 Russia - Saturday, August 07, 2004 at 02:59:51 (PDT)<p>

</td></tr></table></td> <td background="images/tb_right.gif" height="50%" valign="top" width="4"><img src="images/tb_right_topb.gif" height="6" width="3"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="bottom" width="4"><img src="images/tb_left_bottomb.gif" height="6" width="3"></td> <td background="images/tb_right.gif" height="50%" valign="bottom" width="4"><img src="images/tb_right_bottomb.gif" height="6" width="3"></td> </tr> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_bottom.gif" height="4"><img src="images/tb_left_bottomt.gif" height="4" width="8"></td> <td align="right" background="images/tb_bottom.gif" height="4"><img src="images/tb_right_bottomt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> </tbody> </table><center><br><center><table border="0" cellpadding="0" cellspacing="0" width="90%"> <tbody> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_top.gif" height="4"><img src="images/tb_left_topt.gif" height="4" width="8"></td> <td align="right" background="images/tb_top.gif" height="4"><img src="images/tb_right_topt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="top" width="4"><img src="images/tb_left_topb.gif" height="6" width="3"></td> <td colspan="2" rowspan="2"><table width='100%' border=0><tr><td><b>  Hi all<br>
 As all of you are aware, we are in the process of<br>
 bringing forth a news<br>
 letter for x-mec, which from now on, would be<br>
 released in a periodic<br>
 fashion..As part of that, we are currently in the<br>
 process of collecting<br>
 articles. Its a news letter for x-mecians(us) and<br>
 so, there are absolutely<br>
 no restrictions on the topics...So go ahead, unleash<br>
 your imagination and<br>
 translate your thoughts and views into words full of<br>
 life and<br>
 passion....Please send in your articles by August<br>
 15th 2004 to<br>
 <mailto:josephja@sasken.com> josephja@sasken.com.<br>
 Regards<br>
 Joseph Johnson<br>
 CE99~03</b><hr></td></tr>
<tr bgcolor="#cfddd1"><td>Friend&nbsp;&nbsp;<a href="http://xmec.net/view_details.php?.s=1&id=Friend"> </a></td></tr><tr bgcolor="#cfddd1"><td>
 CA USA - Saturday, August 07, 2004 at 02:58:51 (PDT)<p>

</td></tr></table></td> <td background="images/tb_right.gif" height="50%" valign="top" width="4"><img src="images/tb_right_topb.gif" height="6" width="3"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="bottom" width="4"><img src="images/tb_left_bottomb.gif" height="6" width="3"></td> <td background="images/tb_right.gif" height="50%" valign="bottom" width="4"><img src="images/tb_right_bottomb.gif" height="6" width="3"></td> </tr> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_bottom.gif" height="4"><img src="images/tb_left_bottomt.gif" height="4" width="8"></td> <td align="right" background="images/tb_bottom.gif" height="4"><img src="images/tb_right_bottomt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> </tbody> </table><center><br><center><table border="0" cellpadding="0" cellspacing="0" width="90%"> <tbody> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_top.gif" height="4"><img src="images/tb_left_topt.gif" height="4" width="8"></td> <td align="right" background="images/tb_top.gif" height="4"><img src="images/tb_right_topt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="top" width="4"><img src="images/tb_left_topb.gif" height="6" width="3"></td> <td colspan="2" rowspan="2"><table width='100%' border=0><tr><td><b> Funny site</b><hr></td></tr>
<tr bgcolor="#cfddd1"><td>33/1995&nbsp;&nbsp;<a href="http://xmec.net/view_details.php?.s=1&id=33/1995">james</a></td></tr><tr bgcolor="#cfddd1"><td>
 US USA - Saturday, August 07, 2004 at 01:36:44 (PDT)<p>

</td></tr></table></td> <td background="images/tb_right.gif" height="50%" valign="top" width="4"><img src="images/tb_right_topb.gif" height="6" width="3"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="bottom" width="4"><img src="images/tb_left_bottomb.gif" height="6" width="3"></td> <td background="images/tb_right.gif" height="50%" valign="bottom" width="4"><img src="images/tb_right_bottomb.gif" height="6" width="3"></td> </tr> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_bottom.gif" height="4"><img src="images/tb_left_bottomt.gif" height="4" width="8"></td> <td align="right" background="images/tb_bottom.gif" height="4"><img src="images/tb_right_bottomt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> </tbody> </table><center><br><center><table border="0" cellpadding="0" cellspacing="0" width="90%"> <tbody> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_top.gif" height="4"><img src="images/tb_left_topt.gif" height="4" width="8"></td> <td align="right" background="images/tb_top.gif" height="4"><img src="images/tb_right_topt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="top" width="4"><img src="images/tb_left_topb.gif" height="6" width="3"></td> <td colspan="2" rowspan="2"><table width='100%' border=0><tr><td><b> Testing</b><hr></td></tr>
<tr bgcolor="#cfddd1"><td>33/1995&nbsp;&nbsp;<a href="http://xmec.net/view_details.php?.s=1&id=33/1995">Robi</a></td></tr><tr bgcolor="#cfddd1"><td>
Texas USA - Monday, July 12, 2004 at 03:40:15 (PDT)<p>
</td></tr></table></td> <td background="images/tb_right.gif" height="50%" valign="top" width="4"><img src="images/tb_right_topb.gif" height="6" width="3"></td> </tr> <tr> <td background="images/tb_left.gif" height="50%" valign="bottom" width="4"><img src="images/tb_left_bottomb.gif" height="6" width="3"></td> <td background="images/tb_right.gif" height="50%" valign="bottom" width="4"><img src="images/tb_right_bottomb.gif" height="6" width="3"></td> </tr> <tr> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> <td align="left" background="images/tb_bottom.gif" height="4"><img src="images/tb_left_bottomt.gif" height="4" width="8"></td> <td align="right" background="images/tb_bottom.gif" height="4"><img src="images/tb_right_bottomt.gif" height="4" width="8"></td> <td height="4" width="4"><img src="images/corner.gif" height="4" width="4"></td> </tr> </tbody> </table><center><br>
<!--end-->
<?php
include 'footer.php';
?>
