<?php
// DO NOT EDIT THIS FILE.  USE THE ADMIN


// one-time-set settings
  $PHORUM['main_table']='forums';
  $PHORUM['dbtype']='mysql';

// Global Settings
  $PHORUM['started']=1;
  $PHORUM['DefaultDisplay']='30';
  $PHORUM['DefaultEmail']='xmec@xmec.net';
  $PHORUM['PhorumMailCode']='';
  $PHORUM['UseCookies']='1';
  $PHORUM['SortForums']='1';
  $PHORUM['ActiveForums']='4';
  $PHORUM['TimezoneOffset']='0';

  $PHORUM['forum_url']='http://www.xmec.net/phorum';
  $PHORUM['admin_url']='http://www.xmec.net/phorum/nimida/index.php';

  $PHORUM['AllowAttachments']='0';
  $PHORUM['AttachmentDir']='';
  $PHORUM['AttachmentSizeLimit']='';
  $PHORUM['AttachmentFileTypes']='';
  $PHORUM['MaximumNumberAttachments']='0';

  $PHORUM['ext']='php';
  $PHORUM['forum_page']='index';
  $PHORUM['list_page']='list';
  $PHORUM['search_page']='search';
  $PHORUM['read_page']='read';
  $PHORUM['post_page']='post';
  $PHORUM['violation_page']='violation';
  $PHORUM['down_page']='down';
  $PHORUM['attach_page']='attach';
  $PHORUM['default_lang']='lang/english.php';
  $PHORUM['default_body_color']='#FFFFFF';
  $PHORUM['default_body_link_color']='#0000FF';
  $PHORUM['default_body_vlink_color']='#330000';
  $PHORUM['default_body_alink_color']='#FF0000';
  $PHORUM['default_table_width']='90%';
  $PHORUM['default_table_header_color']='#000000';
  $PHORUM['default_table_header_font_color']='#FFFFFF';
  $PHORUM['default_table_body_color_1']='#FFFFFF';
  $PHORUM['default_table_body_font_color_1']='#0000FF';
  $PHORUM['default_table_body_color_2']='#FFFFFF';
  $PHORUM['default_table_body_font_color_2']='#008000';
  $PHORUM['default_nav_color']='#F0E493';
  $PHORUM['default_nav_font_color']='#2211FF';

  // expand all the above into vars for legacy code.
  while(list($key, $value)=each($PHORUM)){
    $$key=$PHORUM[$key];
  }

  // database variables
  $PHORUM['DatabaseServer']='www.xmec.net';
  $PHORUM['DatabaseName']='xmec';
  $PHORUM['DatabaseUser']='xmec';
  $PHORUM['DatabasePassword']='raskals';



?>