#!/usr/bin/perl
##############################################################################
#GuestbookVersion2.3.1#
#Copyright1996MattWrightmattw@worldwidemart.com#
#Created4/21/95LastModified10/29/95#
#ScriptsArchiveat:http://www.worldwidemart.com/scripts/#
##############################################################################
#COPYRIGHTNOTICE#
#Copyright1996MatthewM.WrightAllRightsReserved.#
##
#Guestbookmaybeusedandmodifiedfreeofchargebyanyonesolongas#
#thiscopyrightnoticeandthecommentsaboveremainintact.Byusingthis#
#codeyouagreetoindemnifyMatthewM.Wrightfromanyliabilitythat#
#mightarisefromit'suse.#
##
#Sellingthecodeforthisprogramwithoutpriorwrittenconsentis#
#expresslyforbidden.Inotherwords,pleaseaskfirstbeforeyoutryand#
#makemoneyoffofmyprogram.#
##
#ObtainpermissionbeforeredistributingthissoftwareovertheInternetor#
#inanyothermedium.	Inallcasescopyrightandheadermustremainintact.#
##############################################################################
#SetVariables
$guestbookurl="http://www.xmec.net/guestbook.php";
$guestbookreal="/usr162/home/x/m/xmec/public_html/guestbook.php";
$guestlog="/usr162/home/x/m/xmec/public_html/guestbook/guestlog.html";
$cgiurl="http://xmec.net/guestbook/guestbook.pl";
$date_command="/bin/date";
#SetYourOptions:
$mail=0;#1=Yes;0=No
$uselog=1;#1=Yes;0=No
$linkmail=1;#1=Yes;0=No
$separator=0;#1=<hr>;0=<p>
$redirection=1;#1=Yes;0=No
$entry_order=1;#1=Newestentriesaddedfirst;
#0=NewestEntriesaddedlast.
$remote_mail=0;#1=Yes;0=No
$allow_html=1;#1=Yes;0=No
$line_breaks=1; #1=Yes;0=No
#Ifyouanswered1to$mailor$remote_mailyouwillneedtofillout
#thesevariablesbelow:
$mailprog='/usr/sbin/sendmail';
$recipient='webmaster@xmec.net';
#Done
##############################################################################
#GettheDateforEntry
$date=`$date_command+"%A,%B%d,%Yat%T(%Z)"`;chop($date);
$shortdate=`$date_command+"%D%T%Z"`;chop($shortdate);
#Gettheinput
read(STDIN,$buffer,$ENV{'CONTENT_LENGTH'});
#Splitthename-valuepairs
@pairs=split(/&/,$buffer);
foreach$pair(@pairs){
($name,$value)=split(/=/,$pair);
#Un-Webifyplussignsand%-encoding
$value=~tr/+//;
$value=~s/%([a-fA-F0-9][a-fA-F0-9])/pack("C",hex($1))/eg;
$value=~s/<!--(.|\n)*-->//g;
if($allow_html!=1){
$value=~s/<([^>]|\n)*>//g;
}
$FORM{$name}=$value;
}
#PrinttheBlankResponseSubroutines
&no_commentsunless$FORM{'comments'};
&no_nameunless$FORM{'realname'};
#BegintheEditingoftheGuestbookFile
open(FILE,"$guestbookreal")||die"Can'tOpen$guestbookreal:$!\n";
@LINES=<FILE>;
close(FILE);
$SIZE=@LINES;
#OpenLinkFiletoOutput
open(GUEST,">$guestbookreal")||die"Can'tOpen$guestbookreal:$!\n";
for($i=0;$i<=$SIZE;$i++){
$_=$LINES[$i];
if(/<!--begin-->/){
if($entry_ordereq'1'){
printGUEST"<!--begin-->\n";
}
	printGUEST'<center><tableborder="0"cellpadding="0"cellspacing="0"width="90%"><tbody><tr><tdheight="4"width="4"><imgsrc="images/corner.gif"height="4"width="4"></td><tdalign="left"background="images/tb_top.gif"height="4"><imgsrc="images/tb_left_topt.gif"height="4"width="8"></td><tdalign="right"background="images/tb_top.gif"height="4"><imgsrc="images/tb_right_topt.gif"height="4"width="8"></td><tdheight="4"width="4"><imgsrc="images/corner.gif"height="4"width="4"></td></tr><tr><tdbackground="images/tb_left.gif"height="50%"valign="top"width="4"><imgsrc="images/tb_left_topb.gif"height="6"width="3"></td><tdcolspan="2"rowspan="2">';

if($line_breaks==1){
$FORM{'comments'}=~s/\cM\n/<br>\n/g;
}
	printGUEST"<tablewidth='100%'border=0>";
printGUEST"<tr><td><b>$FORM{'comments'}</b><hr></td></tr>\n";
	printGUEST"<trbgcolor=\"#cfddd1\"><td>";
if($FORM{'url'}){
printGUEST"<ahref=\"http:\/\/$FORM{'url'}\">$FORM{'realname'}</a>";
}
else{
printGUEST"$FORM{'realname'}";
}
if($FORM{'username'}){
if($linkmaileq'1'){
printGUEST"\&lt;<ahref=\"mailto:$FORM{'username'}\">";
printGUEST"$FORM{'username'}</a>\&gt;";
}
else{
printGUEST"&lt;$FORM{'username'}&gt;";
}
}
printGUEST"</td></tr><trbgcolor=\"#cfddd1\"><td>\n";
if($FORM{'city'}){
printGUEST"$FORM{'city'},";
}

if($FORM{'state'}){
printGUEST"$FORM{'state'}";
}
if($FORM{'country'}){
printGUEST"$FORM{'country'}";
}
if($separatoreq'1'){
printGUEST"-$date<hr>\n\n";
}
else{
printGUEST"-$date<p>\n\n";
}
	printGUEST"</td></tr></table>";
if($entry_ordereq'0'){
printGUEST"<!--begin-->\n";
}
printGUEST'</td><tdbackground="images/tb_right.gif"height="50%"valign="top"width="4"><imgsrc="images/tb_right_topb.gif"height="6"width="3"></td></tr><tr><tdbackground="images/tb_left.gif"height="50%"valign="bottom"width="4"><imgsrc="images/tb_left_bottomb.gif"height="6"width="3"></td><tdbackground="images/tb_right.gif"height="50%"valign="bottom"width="4"><imgsrc="images/tb_right_bottomb.gif"height="6"width="3"></td></tr><tr><tdheight="4"width="4"><imgsrc="images/corner.gif"height="4"width="4"></td><tdalign="left"background="images/tb_bottom.gif"height="4"><imgsrc="images/tb_left_bottomt.gif"height="4"width="8"></td><tdalign="right"background="images/tb_bottom.gif"height="4"><imgsrc="images/tb_right_bottomt.gif"height="4"width="8"></td><tdheight="4"width="4"><imgsrc="images/corner.gif"height="4"width="4"></td></tr></tbody></table><center><br>';
}
else{
printGUEST$_;
}
}
close(GUEST);
#LogTheEntry
if($uselogeq'1'){
&log('entry');
}

#########
#Options
#MailOption
if($maileq'1'){
open(MAIL,"|$mailprog$recipient")||die"Can'topen$mailprog!\n";
printMAIL"Reply-to:$FORM{'username'}($FORM{'realname'})\n";
printMAIL"From:$FORM{'username'}($FORM{'realname'})\n";
printMAIL"Subject:EntrytoGuestbook\n\n";
printMAIL"Youhaveanewentryinyourguestbook:\n\n";
printMAIL"------------------------------------------------------\n";
printMAIL"$FORM{'comments'}\n";
printMAIL"$FORM{'realname'}";
if($FORM{'username'}){
printMAIL"<$FORM{'username'}>";
}
printMAIL"\n";
if($FORM{'city'}){
printMAIL"$FORM{'city'},";
}
if($FORM{'state'}){
printMAIL"$FORM{'state'}";
}
if($FORM{'country'}){
printMAIL"$FORM{'country'}";
}
printMAIL"-$date\n";
printMAIL"------------------------------------------------------\n";
close(MAIL);
}
if($remote_maileq'1'&&$FORM{'username'}){
open(MAIL,"|$mailprog-t")||die"Can'topen$mailprog!\n";
printMAIL"To:$FORM{'username'}\n";
printMAIL"From:$recipient\n";
printMAIL"Subject:EntrytoGuestbook\n\n";
printMAIL"Thankyouforaddingtomyguestbook.\n\n";
printMAIL"------------------------------------------------------\n";
printMAIL"$FORM{'comments'}\n";
printMAIL"$FORM{'realname'}";
if($FORM{'username'}){
printMAIL"<$FORM{'username'}>";
}
printMAIL"\n";
if($FORM{'city'}){
printMAIL"$FORM{'city'},";
}
if($FORM{'state'}){
printMAIL"$FORM{'state'}";
}
if($FORM{'country'}){
printMAIL"$FORM{'country'}";
}
printMAIL"-$date\n";
printMAIL"------------------------------------------------------\n";
close(MAIL);
}
#PrintOutInitialOutputLocationHeading
if($redirectioneq'1'){
print"Location:$guestbookurl\n\n";
}
else{
&no_redirection;
}
#######################
#Subroutines
subno_comments{
print"Content-type:text/html\n\n";
print"<html><head><title>NoComments</title></head>\n";
print"<body><h1>YourCommentsappeartobeblank</h1>\n";
print"Thecommentsectionintheguestbookfilloutformappears\n";
print"tobeblankandthereforetheGuestbookAdditionwasnot\n";
print"added.Pleaseenteryourcommentsbelow.<p>\n";
print"<formmethod=POSTaction=\"$cgiurl\">\n";
print"YourName:<inputtype=textname=\"realname\"size=30";
print"value=\"$FORM{'realname'}\"><br>\n";
print"E-Mail:<inputtype=textname=\"username\"";
print"value=\"$FORM{'username'}\"size=40><br>\n";
print"City:<inputtype=textname=\"city\"value=\"$FORM{'city'}\"";
print"size=15>,State:<inputtype=textname=\"state\"";
print"value=\"$FORM{'state'}\"size=15>Country:<inputtype=text";
print"name=\"country\"value=\"$FORM{'country'}\"size=15><p>\n";
print"Comments:<br>\n";
print"<textareaname=\"comments\"COLS=60ROWS=4></textarea><p>\n";
print"<inputtype=submit>*<inputtype=reset></form><hr>\n";
print"Returntothe<ahref=\"$guestbookurl\">Guestbook</a>.";
print"\n</body></html>\n";
#LogTheError
if($uselogeq'1'){
&log('no_comments');
}
exit;
}
subno_name{
print"Content-type:text/html\n\n";
print"<html><head><title>NoName</title></head>\n";
print"<body><h1>YourNameappearstobeblank</h1>\n";
print"TheNameSectionintheguestbookfilloutformappearsto\n";
print"beblankandthereforeyourentrytotheguestbookwasnot\n";
print"added.Pleaseaddyournameintheblankbelow.<p>\n";
print"<formmethod=POSTaction=\"$cgiurl\">\n";
print"YourName:<inputtype=textname=\"realname\"size=30><br>\n";
print"E-Mail:<inputtype=textname=\"username\"";
print"value=\"$FORM{'username'}\"size=40><br>\n";
print"City:<inputtype=textname=\"city\"value=\"$FORM{'city'}\"";
print"size=15>,State:<inputtype=textname=\"state\"";
print"value=\"$FORM{'state'}\"size=2>Country:<inputtype=text";
print"value=USAname=\"country\"value=\"$FORM{'country'}\"";
print"size=15><p>\n";
print"Commentshavebeenretained.<p>\n";
print"<inputtype=hiddenname=\"comments\"";
print"value=\"$FORM{'comments'}\">\n";
print"<inputtype=submit>*<inputtype=reset><hr>\n";
print"Returntothe<ahref=\"$guestbookurl\">Guestbook</a>.";
print"\n</body></html>\n";
#LogTheError
if($uselogeq'1'){
&log('no_name');
}
exit;
}
#LogtheEntryorError
sublog{
$log_type=$_[0];
open(LOG,">>$guestlog");
if($log_typeeq'entry'){
printLOG"$ENV{'REMOTE_ADDR'}-[$shortdate]<br>\n";
}
elsif($log_typeeq'no_name'){
printLOG"$ENV{'REMOTE_ADDR'}-[$shortdate]-ERR:NoName<br>\n";
}
elsif($log_typeeq'no_comments'){
printLOG"$ENV{'REMOTE_ADDR'}-[$shortdate]-ERR:No";
printLOG"Comments<br>\n";
}
}
#RedirectionOption
subno_redirection{
#PrintBeginningofHTML
print"Content-Type:text/html\n\n";
print"<html><head><title>ThankYou</title></head>\n";
print"<body><h1>ThankYouForSigningTheGuestbook</h1>\n";
#PrintResponse
print"Thankyouforfillingintheguestbook.Yourentryhas\n";
print"beenaddedtotheguestbook.<hr>\n";
print"Hereiswhatyousubmitted:<p>\n";
#print"<b>$FORM{'comments'}</b><br>\n";
#if($FORM{'url'}){
#print"<ahref=\"http:\/\/$FORM{'url'}\">$FORM{'realname'}</a>";
#}
#else{
#print"$FORM{'realname'}";
#}
#if($FORM{'username'}){
#if($linkmaileq'1'){
#print"&lt;<ahref=\"mailto:$FORM{'username'}\">";
#print"$FORM{'username'}</a>&gt;";
#}
#else{
#print"&lt;$FORM{'username'}&gt;";
#}
#}
#print"<br>\n";
#if($FORM{'city'}){
#print"$FORM{'city'},";
#}
#if($FORM{'state'}){
#print"$FORM{'state'}";
#}
#if($FORM{'country'}){
#print"$FORM{'country'}";
#}
#print"-$date<p>\n";
	print'<center><tableborder="0"cellpadding="0"cellspacing="0"width="90%"><tbody><tr><tdheight="4"width="4"><imgsrc="images/corner.gif"height="4"width="4"></td><tdalign="left"background="images/tb_top.gif"height="4"><imgsrc="images/tb_left_topt.gif"height="4"width="8"></td><tdalign="right"background="images/tb_top.gif"height="4"><imgsrc="images/tb_right_topt.gif"height="4"width="8"></td><tdheight="4"width="4"><imgsrc="images/corner.gif"height="4"width="4"></td></tr><tr><tdbackground="images/tb_left.gif"height="50%"valign="top"width="4"><imgsrc="images/tb_left_topb.gif"height="6"width="3"></td><tdcolspan="2"rowspan="2">';

if($line_breaks==1){
$FORM{'comments'}=~s/\cM\n/<br>\n/g;
}
	print"<tablewidth='100%'border=0>";
print"<tr><td><b>$FORM{'comments'}</b><hr></td></tr>\n";
	print"<trbgcolor=\"#cfddd1\"><td>";
if($FORM{'url'}){
print"<ahref=\"http:\/\/$FORM{'url'}\">$FORM{'realname'}</a>";
}
else{
print"$FORM{'realname'}";
}
if($FORM{'username'}){
if($linkmaileq'1'){
print"\&lt;<ahref=\"mailto:$FORM{'username'}\">";
print"$FORM{'realname'}</a>\&gt;";
}
else{
print"&lt;$FORM{'username'}&gt;";
}
}
print"</td></tr><trbgcolor=\"#cfddd1\"><td>\n";
if($FORM{'city'}){
print"$FORM{'city'},";
}

if($FORM{'state'}){
print"$FORM{'state'}";
}
if($FORM{'country'}){
print"$FORM{'country'}";
}
if($separatoreq'1'){
print"-$date<hr>\n\n";
}
else{
print"-$date<p>\n\n";
}
	print"</td></tr></table>";
if($entry_ordereq'0'){
print"<!--begin-->\n";
}
print'</td><tdbackground="images/tb_right.gif"height="50%"valign="top"width="4"><imgsrc="images/tb_right_topb.gif"height="6"width="3"></td></tr><tr><tdbackground="images/tb_left.gif"height="50%"valign="bottom"width="4"><imgsrc="images/tb_left_bottomb.gif"height="6"width="3"></td><tdbackground="images/tb_right.gif"height="50%"valign="bottom"width="4"><imgsrc="images/tb_right_bottomb.gif"height="6"width="3"></td></tr><tr><tdheight="4"width="4"><imgsrc="images/corner.gif"height="4"width="4"></td><tdalign="left"background="images/tb_bottom.gif"height="4"><imgsrc="images/tb_left_bottomt.gif"height="4"width="8"></td><tdalign="right"background="images/tb_bottom.gif"height="4"><imgsrc="images/tb_right_bottomt.gif"height="4"width="8"></td><tdheight="4"width="4"><imgsrc="images/corner.gif"height="4"width="4"></td></tr></tbody></table><center><br>';

#PrintEndofHTML
print"<hr>\n";
print"<ahref=\"$guestbookurl\">BacktotheGuestbook</a>\n";print"-Youmayneedtoreloaditwhenyougettheretoseeyour\n";
print"entry.\n";
print"</body></html>\n";
exit;
}
